from typing import Tuple

import numpy as np

import torch
from torch import Tensor

from src.datatypes.split import merge_batches, merge_edge_batches, merge_subgraphs
from src.datatypes.sparse import SparseGraph, SparseEdges
from src.noise.core import NoiseProcess


def sample_sequences(
        batch: SparseGraph,
        removal_process: NoiseProcess,
        num_sequences=1,
        num_subsamples=-1,
        return_first=False, # valid if num_subsamples > 0
        need_preparation=True,
        also_return_splits=False
    ):

    """generates a new batch by sampling sequences from the given batch
    using the removal process. First, the maximum length of the sequences
    is determined from the removal process. Then, noise masks are sampled
    from the removal process, and new batches are generated by applying
    the noise masks to the given batch. Then, the 'batch' part is given
    by all samples from time 0 to T-1, the 'surv_batch' are given by all
    samples from time 1 to T. The 'remv_batch' are computed from the 'batch'
    part by applying the inverse of the collected noise masks. Batches at different
    time steps are processed such that the batch.batch tensors are incremented
    by the right amount at that time steps, taking into account the samples
    that stopped before that time step.
    """

    # determine number of nodes at time 0
    n0 = batch.num_nodes_per_sample
    bs = batch.num_graphs

    # determine the maximum length of the sequences
    # which is the max among the max times of the removal process
    max_time = removal_process.get_max_time(n0=n0)
    if isinstance(max_time, int):
        max_max_time = max_time
    elif isinstance(max_time, Tensor) and max_time.numel() == 1:
        max_max_time = int(max_time.item())
    else:
        max_max_time = int(max_time.max().item())

    # prepare the batch
    if need_preparation:
        removal_process.prepare_data(datapoint=batch)

    global_batch_idx = torch.arange(bs, dtype=torch.int32, device=batch.x.device)

    # time tensor
    batch.global_t = torch.zeros(bs, dtype=torch.int32, device=batch.x.device)
    norm_t = removal_process.normalize_reverse_time(t=batch.global_t, n0=n0)
    batch.global_rev_t = norm_t
    batch.global_n0 = n0
    batch.global_nt = n0
    batch.global_batch_idx = global_batch_idx
    batch.global_new_degree = torch.zeros_like(batch.global_n0)

    # get sub-examples
    if num_subsamples >= 0:
        min_t = 1
        max_t = max_max_time
        num_subsamples = min(num_subsamples, max_t)
        if return_first:
            num_subsamples -= 1 # one is the first batch
            min_t = 2 # start from 2
            max_t -= 1 # one less choice
        selected_indices = np.random.choice(max_t, num_subsamples, replace=False) + min_t
        selected_indices = selected_indices.tolist()

    should_append = lambda x: (x in selected_indices or (return_first and x == 0)) if num_subsamples >= 0 else True

    # prepare sequence
    batches = []
    edges = []
    alive_masks = []

    if should_append(0):
        # build empty remv_edges_ba
        remv_edges_ba = SparseEdges(
            edge_index = torch.zeros((2, 0), dtype=torch.int64, device=batch.x.device),
            edge_attr = torch.zeros(0, dtype=torch.float32, device=batch.x.device),
            num_nodes_s = torch.zeros_like(batch.global_n0),
            num_nodes_t = n0,
            num_nodes = n0
        )

        batches.append(batch)
        edges.append(remv_edges_ba)
        alive_masks.append(torch.ones_like(batch.global_n0, dtype=torch.bool)) # all alive

    for t in range(1, max_max_time):

        next_time = batch.global_t + 1

        batch: SparseGraph
        batch, other_batch, _, remv_edges_ba = removal_process.sample_next(
            current_datapoint = batch,
            t = next_time,
            max_time = max_time,
            n0 = n0,
            split = True
        )

        norm_t = removal_process.normalize_reverse_time(t=next_time, n0=n0)

        batch.global_t = next_time
        batch.global_rev_t = norm_t
        batch.global_n0 = n0
        batch.global_nt = batch.num_nodes_per_sample
        batch.global_batch_idx = global_batch_idx
        batch.global_new_degree = torch.zeros_like(batch.global_n0)
        source_batch_idx = other_batch.batch[remv_edges_ba.edge_index[0]]
        batch.global_new_degree.scatter_add_(0, source_batch_idx, torch.ones_like(source_batch_idx))
        batch.global_new_degree += 1 # add 1 to make 0 a special value

        if should_append(t):
            batches.append(batch)
            edges.append(remv_edges_ba)
            alive_masks.append(batch.global_nt > 0) # will stop if number of nodes is 1 (easy case)


    # merge all batches together
    merged_sequences = {}
    merged_sequences['batch'] = merge_batches(batches, alive_masks)
    merged_sequences['remv_edges_ba'] = merge_edge_batches(edges, alive_masks)

    return merged_sequences, max_max_time
