defaults:
    - _self_
    - removal: cluster
    - ../architecture@insertion.architecture: rgcn/classifier
    - ../architecture@halting.architecture: rgcn/classifier


halting:
    architecture:
        params:
            ffn_config:
                ffn_out_dim: 1
