# @package _global_
defaults:
 - override /task: ego-cdgs
 - override /logger: wandb
 - override /method: ifh
 - override /method/trainer: base_trainer
 - override /method/dataloader: [base_dataloader, batch_2, workers_8]
 - override /method/callbacks: ckpt_ema_gin
 - override /method/model/InsertFillHaltModel: [base, use_digress_marg_unf, 1-4-node]


method:
    model:
        InsertFillHaltModel:
            training:
                embed_time: true
            features:
                - indegree
                - nodes_num
                - spectral
            halting:
                architecture:
                    name: MLPModel
            removal:
                schedule:
                    params:
                        block_size_options: [1, 4, 16]
            filler:
                model:
                    DiscreteDenoisingDiffusionModel:
                        embed_time: true
                        features:
                            - indegree
                            - nodes_num
                            - spectral
    trainer:
        max_epochs: 2000
        log_every_n_steps: 400
        check_val_every_n_epoch: 100
        gradient_clip_val: 1.0

    callbacks:
        early_stopping:
            EarlyStopping:
                patience: 10

logger:
    WandbLogger:
        project: ggen-journal-final
        group: ego-bg

config_name: ego-bg


mode: train+eval
compile: true