# @package _global_
method:
    model:
        InsertFillHaltModel:
            filler:
                model:
                    DiscreteDenoisingDiffusionModel:
                        generation:
                            denoising_jump: 2