# @package _global_
defaults:
 - override /task: qm9
 - override /logger: wandb
 - override /method: ifh
 - override /method/trainer: base_trainer
 - override /method/dataloader: [base_dataloader, batch_1024, workers_8]
 - override /method/callbacks: ckpt_ema_fcd
 - override /method/model/InsertFillHaltModel: [base, use_digress_marg_unf, 1-4-node-dfs]


method:
    model:
        InsertFillHaltModel:
            training:
                embed_time: true
            features:
                - indegree
                - nodes_num
            halting:
                architecture:
                    name: MLPModel
            removal:
                schedule:
                    params:
                        block_size_options: [1, 4]
            filler:
                model:
                    DiscreteDenoisingDiffusionModel:
                        embed_time: true
                        features:
                            - indegree
                            - nodes_num
    trainer:
        max_epochs: 1000
        log_every_n_steps: 400
        check_val_every_n_epoch: 10
        gradient_clip_val: 1.0
    
    callbacks:
        early_stopping:
            EarlyStopping:
                patience: 20

logger:
    WandbLogger:
        project: ggen-journal-final
        group: qm9-bg-dfs

config_name: qm9-bg-dfs


mode: train+eval
compile: true